import type { NewCatalogItem } from './types';

export const SAMPLE_CATALOG: NewCatalogItem[] = [
  { title: 'The Hobbit', mediaType: 'book', coverImageUrl: null },
  { title: 'Dune', mediaType: 'book', coverImageUrl: null },
  { title: 'Project Hail Mary', mediaType: 'book', coverImageUrl: null },
  { title: 'The Name of the Wind', mediaType: 'book', coverImageUrl: null },
  { title: '1984', mediaType: 'book', coverImageUrl: null },
  { title: 'The Way of Kings', mediaType: 'book', coverImageUrl: null },
  { title: 'Circe', mediaType: 'book', coverImageUrl: null },
  { title: 'Neuromancer', mediaType: 'book', coverImageUrl: null },
  { title: 'Spirited Away', mediaType: 'movie', coverImageUrl: null },
  { title: 'The Shawshank Redemption', mediaType: 'movie', coverImageUrl: null },
  { title: 'Parasite', mediaType: 'movie', coverImageUrl: null },
  { title: 'Mad Max: Fury Road', mediaType: 'movie', coverImageUrl: null },
  { title: 'Everything Everywhere All at Once', mediaType: 'movie', coverImageUrl: null },
  { title: 'Blade Runner 2049', mediaType: 'movie', coverImageUrl: null },
  { title: 'Spider-Man: Across the Spider-Verse', mediaType: 'movie', coverImageUrl: null },
  { title: 'Whiplash', mediaType: 'movie', coverImageUrl: null },
  { title: 'The Bear', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'releasing' },
  { title: 'Andor', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'released' },
  { title: 'Succession', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'released' },
  { title: 'Breaking Bad', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'released' },
  { title: 'The Last of Us', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'releasing' },
  { title: 'Severance', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'releasing' },
  { title: 'Avatar: The Last Airbender', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'released' },
  { title: 'Shogun', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'released' },
  { title: "Frieren: Beyond Journey's End", mediaType: 'anime', coverImageUrl: null, releaseStatus: 'releasing' },
  { title: 'Attack on Titan', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'released' },
  { title: 'Cowboy Bebop', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'released' },
  { title: 'Mob Psycho 100', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'released' },
  { title: 'Steins;Gate', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'released' },
  { title: 'Vinland Saga', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'releasing' },
  { title: 'Demon Slayer', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'releasing' },
  { title: 'Fullmetal Alchemist: Brotherhood', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'released' },
  { title: 'Fullmetal Alchemist', mediaType: 'manga', coverImageUrl: null },
  { title: 'One Piece', mediaType: 'manga', coverImageUrl: null },
  { title: 'Berserk', mediaType: 'manga', coverImageUrl: null },
  { title: 'Death Note', mediaType: 'manga', coverImageUrl: null },
  { title: 'Chainsaw Man', mediaType: 'manga', coverImageUrl: null },
  { title: 'Monster', mediaType: 'manga', coverImageUrl: null },
  { title: 'Solo Leveling', mediaType: 'manhwa', coverImageUrl: null },
  { title: 'Tower of God', mediaType: 'manhwa', coverImageUrl: null },
  { title: "Omniscient Reader's Viewpoint", mediaType: 'manhwa', coverImageUrl: null },
  { title: 'Hades', mediaType: 'game', coverImageUrl: null },
  { title: 'Elden Ring', mediaType: 'game', coverImageUrl: null },
  { title: 'Hollow Knight', mediaType: 'game', coverImageUrl: null },
  { title: 'The Legend of Zelda: Breath of the Wild', mediaType: 'game', coverImageUrl: null },
  { title: 'Stardew Valley', mediaType: 'game', coverImageUrl: null },
  { title: 'Disco Elysium', mediaType: 'game', coverImageUrl: null },
  { title: 'Celeste', mediaType: 'game', coverImageUrl: null },
  { title: "Baldur's Gate 3", mediaType: 'game', coverImageUrl: null },
  { title: 'Hades II', mediaType: 'game', coverImageUrl: null },
];
