import type { NewCatalogItem } from './types';

export const SAMPLE_CATALOG: NewCatalogItem[] = [
  { title: 'The Hobbit', mediaType: 'book', coverImageUrl: null, totalPages: 310 },
  { title: 'Dune', mediaType: 'book', coverImageUrl: null, totalPages: 688 },
  { title: 'Project Hail Mary', mediaType: 'book', coverImageUrl: null, totalPages: 496 },
  { title: 'The Name of the Wind', mediaType: 'book', coverImageUrl: null, totalPages: 662 },
  { title: '1984', mediaType: 'book', coverImageUrl: null, totalPages: 328 },
  { title: 'The Way of Kings', mediaType: 'book', coverImageUrl: null, totalPages: 1007 },
  { title: 'Circe', mediaType: 'book', coverImageUrl: null, totalPages: 393 },
  { title: 'Neuromancer', mediaType: 'book', coverImageUrl: null, totalPages: 271 },
  { title: 'Spirited Away', mediaType: 'movie', coverImageUrl: null },
  { title: 'The Shawshank Redemption', mediaType: 'movie', coverImageUrl: null },
  { title: 'Parasite', mediaType: 'movie', coverImageUrl: null },
  { title: 'Mad Max: Fury Road', mediaType: 'movie', coverImageUrl: null },
  { title: 'Everything Everywhere All at Once', mediaType: 'movie', coverImageUrl: null },
  { title: 'Blade Runner 2049', mediaType: 'movie', coverImageUrl: null },
  { title: 'Spider-Man: Across the Spider-Verse', mediaType: 'movie', coverImageUrl: null },
  { title: 'Whiplash', mediaType: 'movie', coverImageUrl: null },
  { title: 'The Bear', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'releasing', totalEpisodes: 38 },
  { title: 'Andor', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'released', totalEpisodes: 24 },
  { title: 'Succession', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'released', totalEpisodes: 39 },
  { title: 'Breaking Bad', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'released', totalEpisodes: 62 },
  { title: 'The Last of Us', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'releasing', totalEpisodes: 16 },
  { title: 'Severance', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'releasing', totalEpisodes: 19 },
  { title: 'Avatar: The Last Airbender', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'released', totalEpisodes: 61 },
  { title: 'Shogun', mediaType: 'tv', coverImageUrl: null, releaseStatus: 'released', totalEpisodes: 10 },
  { title: "Frieren: Beyond Journey's End", mediaType: 'anime', coverImageUrl: null, releaseStatus: 'releasing', totalEpisodes: 28 },
  { title: 'Attack on Titan', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'released', totalEpisodes: 94 },
  { title: 'Cowboy Bebop', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'released', totalEpisodes: 26 },
  { title: 'Mob Psycho 100', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'released', totalEpisodes: 37 },
  { title: 'Steins;Gate', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'released', totalEpisodes: 24 },
  { title: 'Vinland Saga', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'releasing', totalEpisodes: 48 },
  { title: 'Demon Slayer', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'releasing', totalEpisodes: 63 },
  { title: 'Fullmetal Alchemist: Brotherhood', mediaType: 'anime', coverImageUrl: null, releaseStatus: 'released', totalEpisodes: 64 },
  { title: 'Fullmetal Alchemist', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'japanese', totalChapters: 116 },
  { title: 'One Piece', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'japanese', totalChapters: 1122 },
  { title: 'Berserk', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'japanese', totalChapters: 377 },
  { title: 'Death Note', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'japanese', totalChapters: 108 },
  { title: 'Chainsaw Man', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'japanese', totalChapters: 180 },
  { title: 'Monster', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'japanese', totalChapters: 162 },
  { title: 'Solo Leveling', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'south_korean', totalChapters: 179 },
  { title: 'Tower of God', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'south_korean', totalChapters: 650 },
  { title: "Omniscient Reader's Viewpoint", mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'south_korean', totalChapters: 220 },
  { title: "Heaven Official's Blessing", mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'chinese', totalChapters: 120 },
  { title: 'Mo Dao Zu Shi', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'chinese', totalChapters: 125 },
  { title: 'Watchmen', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'american', totalPages: 416 },
  { title: 'Saga', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'american', totalPages: 1500 },
  { title: 'Invincible', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'american', totalPages: 2800 },
  { title: 'The Sandman', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'american', totalPages: 2000 },
  { title: 'Maus', mediaType: 'comic', coverImageUrl: null, mangaOrigin: 'american', totalPages: 296 },
  { title: 'Hades', mediaType: 'game', coverImageUrl: null },
  { title: 'Elden Ring', mediaType: 'game', coverImageUrl: null },
  { title: 'Hollow Knight', mediaType: 'game', coverImageUrl: null },
  { title: 'The Legend of Zelda: Breath of the Wild', mediaType: 'game', coverImageUrl: null },
  { title: 'Stardew Valley', mediaType: 'game', coverImageUrl: null },
  { title: 'Disco Elysium', mediaType: 'game', coverImageUrl: null },
  { title: 'Celeste', mediaType: 'game', coverImageUrl: null },
  { title: "Baldur's Gate 3", mediaType: 'game', coverImageUrl: null },
  { title: 'Hades II', mediaType: 'game', coverImageUrl: null },
];
